#%RAML 1.0 DataType
type: object
properties:
  phoneCountry:
    required: true
    type: string
    example: "+91"
  phoneNumber:
    required: true
    type: string
    example: "8654231456"
  OTP:
    required: true
    type: string
    example: "123456"


